### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Kaelthalon** [McJty/ElementalDimensions#14]
I went to check this mod out by itself in 1.12.2, but the game crashes while loading Minecraft.

https://pastebin.com/kj4jZR6c

Mods loaded:
Elemental Dimensions
ElecCore | Rendering Library

**Comment by McJty** [comment]
Versions please?

**Comment by Kaelthalon** [comment]
1.12-0.1.3

**Comment by McJty** [comment]
Versions of Elemental Dimensions and ElecCore. Not sure what that one is?

**Comment by Kaelthalon** [comment]
eleccore            | 1.7.431      | ElecCore-1.11-1.7.431.jar
elementaldimensions | 0.1.3        | elementaldimensions-1.12-0.1.3.jar

**Comment by McJty** [comment]
ElecCore-1.11-1.7.431.jar
That's ElecCore for 1.11. Please use the 1.12 version

**Comment by Kaelthalon** [comment]
The Twitch Client shows me this version...

**Comment by Kaelthalon** [comment]
Oh I see now, ElecCore needs to be 1.12

**Comment by McJty** [comment]
Well not much I can do about that. It is certainly the wrong version

**Comment by Kaelthalon** [comment]
I'll have to find a download, it's not in the Twitch Client yet.

**Comment by Kaelthalon** [comment]
Thanks for the quick response though!

**Comment by McJty** [comment]
https://minecraft.curseforge.com/projects/eleccore-rendering-library/files

**Comment by Kaelthalon** [comment]
I appears he hasn't updated yet, latest version is 1.11

**Comment by Kaelthalon** [comment]
I'll play around with it in 1.11 though until he updates.

**Comment by McJty** [comment]
He has. Check those downloads. There are 1.12 versions

**Comment by Kaelthalon** [comment]
Oh... ignore me, I'm apparently stupid.
