### ISSUE TITLE
World not loading when updated to 0.0.3 version

### ISSUE THREAD

**Issue by jonabrv1965** [McJty/ElementalDimensions#2]
Hi McJty, here the log as requested in Curseforge.... Keep in mind : I can load the very same world using 0.0.1 version, but when upgrade to 0.0.3 cannot (the loader stops in a brown window with a "0%" label in it, the only way to bypass this is to kill the javaw tasks. If downgraded to 0.0.1 I can load the world...Weird!

And keep in mind also, that in 0.0.1, my rune of earth does not work, it does nothing if I right click a portal dialer...

**Comment by jonabrv1965** [comment]
[latest - Copy.zip](https://github.com/McJty/ElementalDimensions/files/441180/latest.-.Copy.zip)

**Comment by McJty** [comment]
What if you make a new world in 0.0.3? Does that work?

**Comment by jonabrv1965** [comment]
Hi, I tried with a new world and took more than 5 mins to load (find this by accident), but finally load it. This gave me a light about the old world, so I try to load it and wait patiently and effectively it loads but take more than 10 minutes... I´m attaching the log for this successful load...
[latest success load 003.zip](https://github.com/McJty/ElementalDimensions/files/441551/latest.success.load.003.zip)

But, the right click does not work either in this 0.3 version. 

I think could be some kind of conflict with other mod, I will try to isolate this but will take time (with this load times). Any ideas very welcome... :-)

**Comment by McJty** [comment]
I don't know if it is related to your problem but I see massive amounts of crashes from quantumflux in your log. This could certainly cause big slowdowns. It could be that this is the mod that prevents Elemental Dimensions from working. Not sure where the bug is though

**Comment by jonabrv1965** [comment]
Thanks for the heads up. Removing quantumflux now (replaced by flux networks :-). I'll keep you posted...

**Comment by jonabrv1965** [comment]
Hi McJty, definitely is not your mod, I'm facing weird things in my MC/World (including dissapeaing tile entities and that some times the world does not load, but without changing anything, trying later it load ok...!?!) accordingly to the logs is something with the network. I will setup another laptop (lower specs, but enough to test) and will try this very same setup (a rough copy of the .minecraft folder) to determine if its hardware related... Please close this ticket, as I said, this issue is not related to your mod (at least the load part). Thank you very much for your support! (keep your nice work with your others mods!! I do enjoy RFTools, and deepresonance and when feasible, will try dimensions!)
