### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by warrenher** [McJty/ElementalDimensions#27]
See this crash report: https://paste.dimdev.org/ivaxulojic.mccrash
I am using mcjtylib-1.12-3.5.0, ElementalDimensions 1.12-0.3.4, and  ElecCore-1.12.2-1.9.452.

**Comment by Dayyer1** [comment]
I’m getting the same crash.

**Comment by McJty** [comment]
I'll fix this soon

**Comment by McJty** [comment]
Fixed
