### ISSUE TITLE
[0.1.0-1.11.2] Crash related to Random Things

### ISSUE THREAD

**Issue by starg09** [McJty/ElementalDimensions#3]
Seems to be related to a "spirit" entity?

[Crash log](https://gist.github.com/starg09/2cd84b119dd3476ecf770bccacdffab3)

Disabling either one of the mods solves the issue.

**Comment by Elec332** [comment]
both mods are using the same name for the "spirit" mob, causing conflicts

**Comment by McJty** [comment]
I'm looking at this

**Comment by McJty** [comment]
Fixed in 0.1.1 which I'm about to release
