### ISSUE TITLE
Creative tab icon causes crash

### ISSUE THREAD

**Issue by wizard1399** [McJty/ElementalDimensions#5]
Using single player and legacy launcher for Mac OS.

How to reproduce bug:
Open a single player world  go into creative mode.
Use the arrows at the top of the screen to scroll until you get to the view with your mods stuff.
You should get a crash and the crash report will say the creative tab renderer caused the crash.
Through trial and error I figured out it was this mod that caused the crash.

**Comment by McJty** [comment]
I could not exactly reproduce this crash (also you didn't provide a crash log so I had no idea where to look) but I did fix an issue in the creative tab so maybe that helps. If not make a new ticket and this time give a crashlog with it. That's *always* required.

Fix will be in next version
