### ISSUE TITLE
[1.12.1] TOP error when right clicking on Portal Dialer

### ISSUE THREAD

**Issue by b0bst3r** [McJty/ElementalDimensions#9]
Not sure why I right clicked it but still 

http://i.imgur.com/JnMo5BW.png

theoneprobe-1.12-1.4.17.jar
ElecCore-1.12-1.8.430.jar
elementaldimensions-1.12-0.1.2.jar

**Comment by McJty** [comment]
Can you show me your logs?

**Comment by b0bst3r** [comment]
Ahh this what you're after - http://pastebin.ubuntu.com/25382957/ ?

**Comment by McJty** [comment]
yes thanks!

**Comment by McJty** [comment]
Fixed next release
